services:
  - type: web
    name: fdqh-app
    runtime: node
    plan: free
    region: singapore
    branch: main
    autoDeploy: true
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: "20"
